services:
  patient_db:
    image: mongo:8.0.4
    container_name: patient_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - patient_network

  patient_api:
    build: .
    restart: always
    container_name: patient_api
    environment:
      PORT_APP: 9292
      JWT_SECRET: 123456789
    ports:
      - "9292:9292"
    depends_on:
      - patient_db
    networks:
      - patient_network

networks:
  patient_network:
    driver: bridge

volumes:
  mongo_data: